In [4]:
import pandas as pd
import numpy as np
import seaborn as snsi
import numpy as np
import pandas as pd
import seaborn as sns

In [24]:
WHR2015 = pd.read_csv(r'C:\Users\Jonathan\Desktop\Data Science workbench\FINAL Project 2\Dataset\2015.csv')

In [25]:
WHR2015.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [23]:
WHSasa = pd.read_csv(r'C:\Users\Jonathan\Desktop\Data Science workbench\FINAL Project 2\Dataset\alcoholSubstanceAbuse.csv')
WHSalbss = pd.read_csv(r'C:\Users\Jonathan\Desktop\Data Science workbench\FINAL Project 2\Dataset\atLeastBasicSanitizationServices.csv')
WHSbdws = pd.read_csv(r'C:\Users\Jonathan\Desktop\Data Science workbench\FINAL Project 2\Dataset\basicDrinkingWaterServices.csv')
WHScfat = pd.read_csv(r'C:\Users\Jonathan\Desktop\Data Science workbench\FINAL Project 2\Dataset\cleanFuelAndTech.csv')
WHScsr = pd.read_csv(r'C:\Users\Jonathan\Desktop\Data Science workbench\FINAL Project 2\Dataset\crudeSuicideRates.csv')
WHSimr = pd.read_csv(r'C:\Users\Jonathan\Desktop\Data Science workbench\FINAL Project 2\Dataset\infantMortalityRate.csv')
WHSleab = pd.read_csv(r'C:\Users\Jonathan\Desktop\Data Science workbench\FINAL Project 2\Dataset\lifeExpectancyAtBirth.csv')

In [26]:
WHSasa.head()

,Location,Period,Indicator,Dim1,First Tooltip
0,Afghanistan,2018,Total (recorded+unrecorded) alcohol per capita...,Both sexes,0.210
1,Afghanistan,2018,Total (recorded+unrecorded) alcohol per capita...,Male,0.360
2,Afghanistan,2018,Total (recorded+unrecorded) alcohol per capita...,Female,0.055
3,Afghanistan,2015,Total (recorded+unrecorded) alcohol per capita...,Both sexes,0.210
4,Afghanistan,2015,Total (recorded+unrecorded) alcohol per capita...,Male,0.350

In [21]:
columns = pd.DataFrame(WHR2018, columns)

In [19]:
WHRmerge = pd.merge(2019, 2018)

TypeError: Can only merge Series or DataFrame objects, a <class 'int'> was passed